### ISSUE TITLE
repo url in vscode

### ISSUE THREAD

**Issue by marchage** [markuplint/vscode-markuplint#1]
Hi,

The url in visual studio code points to `https://github.com/git@github.com:YusukeHirao/vscode-markuplint`, which gives a 404. It should probalby be `https://github.com/yusukehirao/vscode-markuplint`.

Hope this helps, Marc

**Comment by marchage** [comment]
Oh forgot - not really an issue - so I'm putting it below this one you may throw it away 🙂 

Markuplint... I know markdown! Markdown in comment blocks 😃? 

No. I was looking for things that make my vue life more easy, this extension came up. It's a html linter, right? I guess I will have to try it out... 👍

**Comment by YusukeHirao** [comment]
@marchage  Hi, Marc.

Thank you, I will fix the broken links soon.

Also, this is HTML Linter. I'd like to deal with Vue, but I plan to prepare a parser as a special plugin.

Markdown ... do you mean to lint inside the "code" block?
